/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.FriendManager;
import Backend.Threads;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author abban
 */
public class AddFriendScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddFriendScreen
     */
    
    private String Username;
    
    public AddFriendScreen() {
        initComponents();
        
        
    }
    public AddFriendScreen(String username) {
        initComponents();
        
        Username = username;
        
        Runnable getReceivingFriendRequest = new Threads(RecievedFriendRequestList, Username);
        
        Thread thread = new Thread(getReceivingFriendRequest);
        
        thread.start();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingBackground1 = new UISupport.SettingBackground();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchFriendTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SendFriendRequestList = new javax.swing.JList<>();
        SendFriendRequestButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RecievedFriendRequestList = new javax.swing.JList<>();
        AcceptFriendRequestButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        SuccessLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Send Friend request");

        jLabel2.setText("Search");

        SearchFriendTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchFriendTextFieldKeyReleased(evt);
            }
        });

        SendFriendRequestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(SendFriendRequestList);

        SendFriendRequestButton.setText("Send");
        SendFriendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFriendRequestButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Accept Friend Request");

        RecievedFriendRequestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        RecievedFriendRequestList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RecievedFriendRequestListFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(RecievedFriendRequestList);

        AcceptFriendRequestButton.setText("Accept");
        AcceptFriendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptFriendRequestButtonActionPerformed(evt);
            }
        });

        GoBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left_arrow_icon.png"))); // NOI18N
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingBackground1Layout = new javax.swing.GroupLayout(settingBackground1);
        settingBackground1.setLayout(settingBackground1Layout);
        settingBackground1Layout.setHorizontalGroup(
            settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingBackground1Layout.createSequentialGroup()
                .addGroup(settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingBackground1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GoBackButton))
                    .addGroup(settingBackground1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(SearchFriendTextField)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addComponent(SendFriendRequestButton)
                            .addComponent(SuccessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcceptFriendRequestButton)
                    .addComponent(jScrollPane2))
                .addGap(86, 86, 86))
        );
        settingBackground1Layout.setVerticalGroup(
            settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
            .addGroup(settingBackground1Layout.createSequentialGroup()
                .addGroup(settingBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingBackground1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GoBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(SearchFriendTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SendFriendRequestButton))
                    .addGroup(settingBackground1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AcceptFriendRequestButton)))
                .addGap(18, 18, 18)
                .addComponent(SuccessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        new HomeScreen(Username).setVisible(true);
        dispose();
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void SearchFriendTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFriendTextFieldKeyReleased
        // TODO add your handling code here:
        Runnable getSendFriendRequest = new Threads(SendFriendRequestList,SearchFriendTextField.getText(),Username);
        
        Thread thread = new Thread(getSendFriendRequest);
        
        thread.start();
    }//GEN-LAST:event_SearchFriendTextFieldKeyReleased

    private void SendFriendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFriendRequestButtonActionPerformed
        // TODO add your handling code here:
        String to = SendFriendRequestList.getSelectedValue();
        try {
            
            boolean result = FriendManager.sendFriendRequest(Username, to);
            
            if(result){
                
                SuccessLabel.setForeground(Color.green);
                SuccessLabel.setText("Friend request sent");
                
            }
            else{
                
                SuccessLabel.setForeground(Color.red);
                SuccessLabel.setText("Friend request failed");
                        
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddFriendScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Runnable getReceivingFriendRequest = new Threads(RecievedFriendRequestList, Username);
        
        Thread thread = new Thread(getReceivingFriendRequest);
        
        thread.start();
        
        
    }//GEN-LAST:event_SendFriendRequestButtonActionPerformed

    private void AcceptFriendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptFriendRequestButtonActionPerformed
        // TODO add your handling code here:
        String from = RecievedFriendRequestList.getSelectedValue();
        
        try {
            
            FriendManager.acceptFriendRequest(Username, from,RecievedFriendRequestList);
            
        } catch (SQLException ex) {
            Logger.getLogger(AddFriendScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AcceptFriendRequestButtonActionPerformed

    private void RecievedFriendRequestListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RecievedFriendRequestListFocusLost
        // TODO add your handling code here:
        Runnable getReceivingFriendRequest = new Threads(RecievedFriendRequestList, Username);
        
        Thread thread = new Thread(getReceivingFriendRequest);
        
        thread.start();
    }//GEN-LAST:event_RecievedFriendRequestListFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFriendScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptFriendRequestButton;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JList<String> RecievedFriendRequestList;
    private javax.swing.JTextField SearchFriendTextField;
    private javax.swing.JButton SendFriendRequestButton;
    private javax.swing.JList<String> SendFriendRequestList;
    private javax.swing.JLabel SuccessLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private UISupport.SettingBackground settingBackground1;
    // End of variables declaration//GEN-END:variables
}
