/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.FriendManager;
import Backend.MessageManager;
import Backend.Threads;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;

/**
 *
 * @author abban
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    
    private String Username;
    private String selectedFriendOrGroup;
    
    public HomeScreen() {
        initComponents();
    }
    
    public HomeScreen(String username) {
        initComponents();
        
        new HomeScreen().setTitle("Welcome to ChatBun");
        
        Username = username;
        
        WelcomeLabel.setText("Welcome: " + username);
        
        setLocationRelativeTo(null);
        
        
        Runnable getFriends = new Threads(username,"Friends",FriendORGroupList);
        Runnable getConnectedAccount = new Threads(username,SwapAccountComboBox);
            
        Thread thread1 = new Thread(getFriends);
        Thread thread2 = new Thread(getConnectedAccount);
        
        thread1.start();
        thread2.start();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeparatorSplitPane = new javax.swing.JSplitPane();
        loginBackground1 = new UISupport.LoginBackground();
        FriendsOrGroupToggleButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FriendORGroupList = new javax.swing.JList<>();
        DeleteMessageButton = new javax.swing.JButton();
        BlockButton = new javax.swing.JButton();
        Separator3 = new javax.swing.JSeparator();
        Separator2 = new javax.swing.JSeparator();
        swapAccountLabel = new javax.swing.JLabel();
        SwapAccountComboBox = new javax.swing.JComboBox<>();
        Separator1 = new javax.swing.JSeparator();
        WelcomeLabel = new javax.swing.JLabel();
        SettingButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        signUpBackground1 = new UISupport.SignUpBackground();
        TalkToLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewMessageTextArea = new javax.swing.JTextArea();
        SendMessageTextField = new javax.swing.JTextField();
        SendMessgeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        FriendsOrGroupToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/friend_icon.png"))); // NOI18N
        FriendsOrGroupToggleButton.setText("Friends");
        FriendsOrGroupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsOrGroupToggleButtonActionPerformed(evt);
            }
        });

        FriendORGroupList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        FriendORGroupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FriendORGroupListMouseClicked(evt);
            }
        });
        FriendORGroupList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                FriendORGroupListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(FriendORGroupList);

        DeleteMessageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_message_icon.png"))); // NOI18N
        DeleteMessageButton.setText("Delete message");
        DeleteMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMessageButtonActionPerformed(evt);
            }
        });

        BlockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/block_icon.png"))); // NOI18N
        BlockButton.setText("Block");
        BlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockButtonActionPerformed(evt);
            }
        });

        swapAccountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change_account_icon.png"))); // NOI18N
        swapAccountLabel.setText("Swap account:");

        SwapAccountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SwapAccountComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SwapAccountComboBoxItemStateChanged(evt);
            }
        });

        WelcomeLabel.setForeground(new java.awt.Color(51, 51, 55));
        WelcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hand_wave_icon.png"))); // NOI18N
        WelcomeLabel.setText("Welcome back ");

        SettingButton.setText("Settings");
        SettingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingButtonActionPerformed(evt);
            }
        });

        RemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_icon.png"))); // NOI18N
        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_icon.png"))); // NOI18N
        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginBackground1Layout = new javax.swing.GroupLayout(loginBackground1);
        loginBackground1.setLayout(loginBackground1Layout);
        loginBackground1Layout.setHorizontalGroup(
            loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBackground1Layout.createSequentialGroup()
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(loginBackground1Layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(swapAccountLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SwapAccountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Separator3)
                                .addComponent(jScrollPane1)
                                .addComponent(Separator2)
                                .addGroup(loginBackground1Layout.createSequentialGroup()
                                    .addComponent(BlockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                    .addComponent(DeleteMessageButton))
                                .addComponent(FriendsOrGroupToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(SettingButton)
                        .addGap(144, 144, 144)
                        .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        loginBackground1Layout.setVerticalGroup(
            loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBackground1Layout.createSequentialGroup()
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(WelcomeLabel))
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(SettingButton)))
                .addGap(18, 18, 18)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SwapAccountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swapAccountLabel))
                .addGap(18, 18, 18)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FriendsOrGroupToggleButton)
                            .addComponent(AddButton))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(loginBackground1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(RemoveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Separator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteMessageButton)
                    .addComponent(BlockButton))
                .addGap(58, 58, 58))
        );

        ViewMessageTextArea.setEditable(false);
        ViewMessageTextArea.setColumns(20);
        ViewMessageTextArea.setRows(5);
        jScrollPane2.setViewportView(ViewMessageTextArea);

        SendMessgeButton.setText("Send");
        SendMessgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessgeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpBackground1Layout = new javax.swing.GroupLayout(signUpBackground1);
        signUpBackground1.setLayout(signUpBackground1Layout);
        signUpBackground1Layout.setHorizontalGroup(
            signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBackground1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpBackground1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBackground1Layout.createSequentialGroup()
                        .addGroup(signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBackground1Layout.createSequentialGroup()
                                .addComponent(SendMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(SendMessgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TalkToLabel))
                        .addGap(65, 65, 65))))
        );
        signUpBackground1Layout.setVerticalGroup(
            signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpBackground1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(TalkToLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendMessgeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loginBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(SeparatorSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(signUpBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SeparatorSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(signUpBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMessageButtonActionPerformed
        // TODO add your handling code here:
        if(FriendsOrGroupToggleButton.getText().equals("Friends")){
            try {
                MessageManager.deleteFriendMessage(Username, selectedFriendOrGroup);
            } catch (SQLException ex) {
                Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                MessageManager.deleteGroupMessage(Username, selectedFriendOrGroup);
            } catch (SQLException ex) {
                Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_DeleteMessageButtonActionPerformed

    private void BlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockButtonActionPerformed
        // TODO add your handling code here:
        boolean friend = FriendsOrGroupToggleButton.getText().equals("Friends");
        boolean block = BlockButton.getText().equals("Block");
        
        Runnable blockFriend = new Threads(Username,selectedFriendOrGroup,friend,block,BlockButton);
        
        Thread thread = new Thread(blockFriend);
        
        thread.start();
        
    }//GEN-LAST:event_BlockButtonActionPerformed

    private void SettingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingButtonActionPerformed
        // TODO add your handling code here:
        new SettingScreen(Username).setVisible(true);
        dispose();
    }//GEN-LAST:event_SettingButtonActionPerformed

    private void FriendsOrGroupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsOrGroupToggleButtonActionPerformed
        // TODO add your handling code here:
        String text = FriendsOrGroupToggleButton.getText();
        
        Runnable toggleFriendAndGroup = new Threads(FriendsOrGroupToggleButton,text,FriendORGroupList,Username);
        
        Thread thread = new Thread(toggleFriendAndGroup);
        
        thread.start();
        
        ViewMessageTextArea.setText("");
        
        TalkToLabel.setText("");
        
    }//GEN-LAST:event_FriendsOrGroupToggleButtonActionPerformed

    private void SendMessgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessgeButtonActionPerformed

       String messageSend = SendMessageTextField.getText();
       String messageRecieved = ViewMessageTextArea.getText();
       boolean friend = FriendsOrGroupToggleButton.getText().equals("Friends");
        
        Runnable sendFriendMessage = new Threads(Username,selectedFriendOrGroup,messageSend,messageRecieved,friend);
        
        Thread thread = new Thread(sendFriendMessage);
        
        thread.start();
    }//GEN-LAST:event_SendMessgeButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String addWhat = FriendsOrGroupToggleButton.getText();
        
        if(addWhat.equals("Friends")){
            
            new AddFriendScreen(Username).setVisible(true);
            dispose();
            
        }else{
            
            new AddGroupScreen(Username).setVisible(true);
            dispose();
            
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void FriendORGroupListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_FriendORGroupListValueChanged
        // TODO add your handling code here:
        selectedFriendOrGroup = FriendORGroupList.getSelectedValue();
        
        boolean friend = FriendsOrGroupToggleButton.getText().equals("Friends");
        
        Runnable getFriendOrGroupMessage = new Threads(ViewMessageTextArea,Username,selectedFriendOrGroup,FriendsOrGroupToggleButton,FriendORGroupList);
        
        Runnable setBlockButton = new Threads(Username,selectedFriendOrGroup,BlockButton,friend);
        
        Thread thread = new Thread(getFriendOrGroupMessage);
        
        Thread thread2 = new Thread(setBlockButton);
        
        thread.start();
        
        thread2.start();
        
        TalkToLabel.setText("You are currently talking to: " + selectedFriendOrGroup);
    }//GEN-LAST:event_FriendORGroupListValueChanged

    private void FriendORGroupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FriendORGroupListMouseClicked
        // https://stackoverflow.com/questions/4344682/double-click-event-on-jlist-element
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            
            new ProfileScreen(Username).setVisible(true);
            dispose();
            
         }
    }//GEN-LAST:event_FriendORGroupListMouseClicked

    private void SwapAccountComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SwapAccountComboBoxItemStateChanged
        // TODO add your handling code here:
        String currentAccount =  (String) SwapAccountComboBox.getSelectedItem();
        String toggleButtonText = FriendsOrGroupToggleButton.getText();
        
        Username = currentAccount;
        
        WelcomeLabel.setText("Welcome: " + Username);
        
        Runnable setNewList = new Threads(Username,toggleButtonText,FriendORGroupList);
        
        Thread thread = new Thread(setNewList);
        
        thread.start();
    }//GEN-LAST:event_SwapAccountComboBoxItemStateChanged

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        if(FriendsOrGroupToggleButton.getText().equals("Friends")){
            try {
                
                FriendManager.removeFriend(Username, selectedFriendOrGroup);
                
                Runnable setNewList = new Threads(Username,"Friends",FriendORGroupList);
        
                Thread thread = new Thread(setNewList);
        
                thread.start();
                
            } catch (SQLException ex) {
                Logger.getLogger(HomeScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            
        }
    }//GEN-LAST:event_RemoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BlockButton;
    private javax.swing.JButton DeleteMessageButton;
    private javax.swing.JList<String> FriendORGroupList;
    private javax.swing.JToggleButton FriendsOrGroupToggleButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JTextField SendMessageTextField;
    private javax.swing.JButton SendMessgeButton;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSplitPane SeparatorSplitPane;
    private javax.swing.JButton SettingButton;
    private javax.swing.JComboBox<String> SwapAccountComboBox;
    private javax.swing.JLabel TalkToLabel;
    private javax.swing.JTextArea ViewMessageTextArea;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private UISupport.LoginBackground loginBackground1;
    private UISupport.SignUpBackground signUpBackground1;
    private javax.swing.JLabel swapAccountLabel;
    // End of variables declaration//GEN-END:variables
}
