/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;

/**
 *
 * @author abban
 */
public class SettingScreen extends javax.swing.JFrame {

    /**
     * Creates new form SettingScreen
     */
    private String Username = "";
    
    DefaultListModel AccountDefaultList = new DefaultListModel();
    String[] tags = {"Main"};
    
    //Code to get currently available font is from https://alvinalexander.com/blog/post/jfc-swing/swing-faq-list-fonts-current-platform/ 
    String fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
    
    DefaultComboBoxModel FontProfileDefaultList = new DefaultComboBoxModel();
    
    
    
    public SettingScreen() {
        initComponents();
        for(int i = 0; i < tags.length; i++){
            AccountDefaultList.addElement(tags[i]);
            this.AccountList.setModel(AccountDefaultList);
        }
        for(int i = 0; i < fonts.length; i++){
            FontProfileDefaultList.addElement(fonts[i]);
            this.fontBioComboBox.setModel(FontProfileDefaultList);
            this.fontMessageComboBox.setModel(FontProfileDefaultList);
        }
    }
    
     public SettingScreen(String username) {
         Username = username;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        settingPanel1 = new UISupport.SettingBackground();
        SettingLabel = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DisplayLayerPane = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FirstColourSideMenuTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LastColourSideMenuTextField = new javax.swing.JTextField();
        loginBackground1 = new UISupport.LoginBackground();
        UpdateSideMenuButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FirstColourTextingScreenTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LastColourTextingScreenTextField = new javax.swing.JTextField();
        UpdateTextingScreenButton = new javax.swing.JButton();
        signUpBackground1 = new UISupport.SignUpBackground();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        FirstcColourProfileScreen = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        LastColourProfileScreenButton = new javax.swing.JTextField();
        profileBackground1 = new UISupport.ProfileBackground();
        UpdateProfileScreen = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fontBioComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fontMessageComboBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        SideMenuColourError = new javax.swing.JLabel();
        UpdateBioDisplayButton = new javax.swing.JButton();
        UpdateMessageButton = new javax.swing.JButton();
        sizeBioSpinner = new javax.swing.JSpinner();
        sizeMessageSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        ProfileLayeredPane = new javax.swing.JLayeredPane();
        DisplayNameLabel = new javax.swing.JLabel();
        DisplayNameTextField = new javax.swing.JTextField();
        UpdateDisplayNameButton = new javax.swing.JButton();
        IconLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        UpdateIconButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UpdateBioButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        AddAccountTextField = new javax.swing.JTextField();
        AddAccountButton = new javax.swing.JButton();
        RemoveAccountButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        UpdateTagsButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        AccountList = new javax.swing.JList<>();
        AutoLoginToggleButton = new javax.swing.JToggleButton();
        ErrorAccountLabel = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        ErrorBioLabel = new javax.swing.JLabel();
        ErrrorDisplayNameLabel = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        ProfileIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SettingLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SettingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/setting_large_icon.png"))); // NOI18N
        SettingLabel.setText("Setting");

        ReturnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left_arrow_icon.png"))); // NOI18N
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account_small_icon.png"))); // NOI18N
        jLabel1.setText("Profile:");

        jLabel7.setText("Change background of side menu");

        jLabel8.setText("First colour:");

        FirstColourSideMenuTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstColourSideMenuTextFieldKeyReleased(evt);
            }
        });

        jLabel9.setText("Last colour:");

        javax.swing.GroupLayout loginBackground1Layout = new javax.swing.GroupLayout(loginBackground1);
        loginBackground1.setLayout(loginBackground1Layout);
        loginBackground1Layout.setHorizontalGroup(
            loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        loginBackground1Layout.setVerticalGroup(
            loginBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        UpdateSideMenuButton.setText("Update");

        jLabel10.setText("Change background of texting screen");

        jLabel11.setText("First colour:");

        jLabel12.setText("Last colour:");

        UpdateTextingScreenButton.setText("Update");

        javax.swing.GroupLayout signUpBackground1Layout = new javax.swing.GroupLayout(signUpBackground1);
        signUpBackground1.setLayout(signUpBackground1Layout);
        signUpBackground1Layout.setHorizontalGroup(
            signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        signUpBackground1Layout.setVerticalGroup(
            signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel13.setText("Change background of profile screen");

        jLabel14.setText("First colour:");

        jLabel15.setText("Last colour:");

        javax.swing.GroupLayout profileBackground1Layout = new javax.swing.GroupLayout(profileBackground1);
        profileBackground1.setLayout(profileBackground1Layout);
        profileBackground1Layout.setHorizontalGroup(
            profileBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        profileBackground1Layout.setVerticalGroup(
            profileBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        UpdateProfileScreen.setText("Update");

        jLabel16.setText("Change the:");

        jLabel17.setText("Text font of bio:");

        jLabel18.setText("Text size of bio:");

        jLabel20.setText("Text font of messages:");

        jLabel21.setText("Text size of messages:");

        fontBioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("This is how it looks like:");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        jLabel24.setText("words");

        fontMessageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("This is how it looks like: ");

        jLabel26.setText("words");

        SideMenuColourError.setText("jLabel2");

        UpdateBioDisplayButton.setText("Update");

        UpdateMessageButton.setText("Update");

        DisplayLayerPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(FirstColourSideMenuTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(LastColourSideMenuTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(loginBackground1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(UpdateSideMenuButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(FirstColourTextingScreenTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(LastColourTextingScreenTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(UpdateTextingScreenButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(signUpBackground1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(FirstcColourProfileScreen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(LastColourProfileScreenButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(profileBackground1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(UpdateProfileScreen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(fontBioComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(fontMessageComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(SideMenuColourError, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(UpdateBioDisplayButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(UpdateMessageButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(sizeBioSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DisplayLayerPane.setLayer(sizeMessageSpinner, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DisplayLayerPaneLayout = new javax.swing.GroupLayout(DisplayLayerPane);
        DisplayLayerPane.setLayout(DisplayLayerPaneLayout);
        DisplayLayerPaneLayout.setHorizontalGroup(
            DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayLayerPaneLayout.createSequentialGroup()
                        .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FirstColourSideMenuTextField)
                                    .addComponent(LastColourSideMenuTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(loginBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(profileBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signUpBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(96, 96, 96))
                    .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                        .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateBioDisplayButton)
                            .addComponent(UpdateMessageButton)
                            .addComponent(jLabel21)
                            .addComponent(sizeBioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeMessageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayLayerPaneLayout.createSequentialGroup()
                        .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25))
                            .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addGap(86, 86, 86))
                    .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                        .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addComponent(FirstColourTextingScreenTextField)
                                .addComponent(jLabel12)
                                .addComponent(LastColourTextingScreenTextField))
                            .addComponent(UpdateTextingScreenButton)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(UpdateProfileScreen)
                            .addComponent(jLabel16)
                            .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LastColourProfileScreenButton, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FirstcColourProfileScreen, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(fontBioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fontMessageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateSideMenuButton)
                            .addComponent(SideMenuColourError))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        DisplayLayerPaneLayout.setVerticalGroup(
            DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(FirstColourSideMenuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(loginBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastColourSideMenuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(SideMenuColourError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateSideMenuButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(FirstColourTextingScreenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(LastColourTextingScreenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayLayerPaneLayout.createSequentialGroup()
                        .addComponent(signUpBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DisplayLayerPaneLayout.createSequentialGroup()
                        .addComponent(UpdateTextingScreenButton)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(FirstcColourProfileScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(LastColourProfileScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(profileBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UpdateProfileScreen)
                .addGap(36, 36, 36)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel5)
                    .addComponent(jLabel24))
                .addGap(7, 7, 7)
                .addComponent(fontBioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addComponent(sizeBioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateBioDisplayButton)
                .addGap(18, 18, 18)
                .addGroup(DisplayLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fontMessageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(sizeMessageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateMessageButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/display_icon.png"))); // NOI18N
        jLabel6.setText("Display");

        DisplayNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Displayname_icon.png"))); // NOI18N
        DisplayNameLabel.setText("Display name:");

        UpdateDisplayNameButton.setText("Update");

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/account_really_small_icon.png"))); // NOI18N
        IconLabel.setText("Icon:");

        UpdateIconButton.setText("Update");

        jLabel3.setText("Bio:");

        UpdateBioButton.setText("Update");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/change_account_icon.png"))); // NOI18N
        jLabel4.setText("Add account:");

        AddAccountButton.setText("Add");
        AddAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccountButtonActionPerformed(evt);
            }
        });

        RemoveAccountButton.setText("Remove");
        RemoveAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAccountButtonActionPerformed(evt);
            }
        });

        UpdateTagsButton.setText("Update");

        jLabel23.setText("Auto-login:");

        AccountList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        AutoLoginToggleButton.setText("Yes");

        ErrorAccountLabel.setForeground(new java.awt.Color(255, 0, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        ErrorBioLabel.setForeground(new java.awt.Color(255, 0, 0));

        ErrrorDisplayNameLabel.setForeground(new java.awt.Color(255, 0, 0));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel27.setText("This is how it looks like:");

        ProfileIconLabel.setText("jLabel28");

        ProfileLayeredPane.setLayer(DisplayNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(DisplayNameTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(UpdateDisplayNameButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(IconLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(UpdateIconButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(UpdateBioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(AddAccountTextField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(AddAccountButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(RemoveAccountButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(UpdateTagsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(AccountList, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(AutoLoginToggleButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(ErrorAccountLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jTextArea1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(ErrorBioLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(ErrrorDisplayNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jComboBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        ProfileLayeredPane.setLayer(ProfileIconLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ProfileLayeredPaneLayout = new javax.swing.GroupLayout(ProfileLayeredPane);
        ProfileLayeredPane.setLayout(ProfileLayeredPaneLayout);
        ProfileLayeredPaneLayout.setHorizontalGroup(
            ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                        .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfileLayeredPaneLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(AccountList, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddAccountTextField)
                                    .addComponent(jSeparator4)
                                    .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                                        .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RemoveAccountButton)
                                            .addComponent(AutoLoginToggleButton)
                                            .addComponent(AddAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 72, Short.MAX_VALUE)))))
                        .addGap(116, 116, 116))
                    .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                        .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateIconButton)
                            .addComponent(ErrrorDisplayNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(UpdateTagsButton)
                            .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpdateBioButton)
                                    .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ErrorBioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ErrorAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                        .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateDisplayNameButton)
                            .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfileLayeredPaneLayout.createSequentialGroup()
                                    .addComponent(IconLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfileLayeredPaneLayout.createSequentialGroup()
                                    .addComponent(DisplayNameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(DisplayNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                        .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayeredPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProfileIconLabel)
                .addGap(128, 128, 128))
        );
        ProfileLayeredPaneLayout.setVerticalGroup(
            ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayeredPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayNameLabel)
                    .addComponent(DisplayNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrrorDisplayNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(UpdateDisplayNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IconLabel)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(ProfileIconLabel)
                .addGap(26, 26, 26)
                .addComponent(UpdateIconButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(UpdateBioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorBioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayeredPaneLayout.createSequentialGroup()
                        .addComponent(AddAccountButton)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveAccountButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AccountList, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddAccountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AutoLoginToggleButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ProfileLayeredPaneLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel23))
                        .addComponent(UpdateTagsButton)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout settingPanel1Layout = new javax.swing.GroupLayout(settingPanel1);
        settingPanel1.setLayout(settingPanel1Layout);
        settingPanel1Layout.setHorizontalGroup(
            settingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReturnButton)
                .addGap(141, 141, 141)
                .addGroup(settingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addComponent(SettingLabel))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(settingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ProfileLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayLayerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        settingPanel1Layout.setVerticalGroup(
            settingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanel1Layout.createSequentialGroup()
                .addGroup(settingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ReturnButton))
                    .addGroup(settingPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(SettingLabel)))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfileLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(DisplayLayerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(settingPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAccountButtonActionPerformed
        // TODO add your handling code here:
        if(AccountDefaultList.elementAt(AccountList.getSelectedIndex()).equals("Main")){
            
        }else{
            AccountDefaultList.removeElementAt(AccountList.getSelectedIndex());
        }
    }//GEN-LAST:event_RemoveAccountButtonActionPerformed

    private void AddAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccountButtonActionPerformed
        // TODO add your handling code here:
        String add = AddAccountTextField.getText();
        
        if(AccountDefaultList.contains(add)){
            AccountDefaultList.addElement(add);
        }
        else{
            
        }
    }//GEN-LAST:event_AddAccountButtonActionPerformed

    private void FirstColourSideMenuTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstColourSideMenuTextFieldKeyReleased
        // TODO add your handling code here:
        try{
            Color.decode(FirstColourSideMenuTextField.getText());
        }
        catch(IllegalArgumentException ex){
            
        }
        
    }//GEN-LAST:event_FirstColourSideMenuTextFieldKeyReleased

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        // TODO add your handling code here:
        new HomeScreen(Username).setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AccountList;
    private javax.swing.JButton AddAccountButton;
    private javax.swing.JTextField AddAccountTextField;
    private javax.swing.JToggleButton AutoLoginToggleButton;
    private javax.swing.JLayeredPane DisplayLayerPane;
    private javax.swing.JLabel DisplayNameLabel;
    private javax.swing.JTextField DisplayNameTextField;
    private javax.swing.JLabel ErrorAccountLabel;
    private javax.swing.JLabel ErrorBioLabel;
    private javax.swing.JLabel ErrrorDisplayNameLabel;
    private javax.swing.JTextField FirstColourSideMenuTextField;
    private javax.swing.JTextField FirstColourTextingScreenTextField;
    private javax.swing.JTextField FirstcColourProfileScreen;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JTextField LastColourProfileScreenButton;
    private javax.swing.JTextField LastColourSideMenuTextField;
    private javax.swing.JTextField LastColourTextingScreenTextField;
    private javax.swing.JLabel ProfileIconLabel;
    private javax.swing.JLayeredPane ProfileLayeredPane;
    private javax.swing.JButton RemoveAccountButton;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JLabel SettingLabel;
    private javax.swing.JLabel SideMenuColourError;
    private javax.swing.JButton UpdateBioButton;
    private javax.swing.JButton UpdateBioDisplayButton;
    private javax.swing.JButton UpdateDisplayNameButton;
    private javax.swing.JButton UpdateIconButton;
    private javax.swing.JButton UpdateMessageButton;
    private javax.swing.JButton UpdateProfileScreen;
    private javax.swing.JButton UpdateSideMenuButton;
    private javax.swing.JButton UpdateTagsButton;
    private javax.swing.JButton UpdateTextingScreenButton;
    private javax.swing.JComboBox<String> fontBioComboBox;
    private javax.swing.JComboBox<String> fontMessageComboBox;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private UISupport.LoginBackground loginBackground1;
    private UISupport.ProfileBackground profileBackground1;
    private UISupport.SettingBackground settingPanel1;
    private UISupport.SignUpBackground signUpBackground1;
    private javax.swing.JSpinner sizeBioSpinner;
    private javax.swing.JSpinner sizeMessageSpinner;
    // End of variables declaration//GEN-END:variables
}
